### ISSUE TITLE
Review component with support of EntityObjectPicker

### ISSUE THREAD

**Issue by evghen1** [web-seven/backstage-plugins#24]
## Issue summary:
When EntityObjectPicker is used in backstage templates, value of selected entity show full object structure, what is not nice for users, because this pickers are made to hide detailed data of entity and improve UX.
## Issue datails:
For improve UX, proposed to create review step component where objects values will be show as links to selected objects.
## Todo:
- [ ] Copy standard review step component and update it with logic for display links to selected entity instead of print object.
- [ ] Make links to open in new browser tab, to not loose data entered by user on review, when it will be clicked.
- [ ] Update scaffolder page in demo application with this custom review step.
